---
title: "LandR Biomass Manual"
subtitle: "v. 0.0.9000"
author: "Edited by: Ceres Barros, Alex M. Chubaty, Ian M. S. Eddy, Eliot J. B. McIntire"
date: "Last updated: `r Sys.Date()`"
site: bookdown::bookdown_site
bibliography:
  - citations/references_Biomass_core.bib
  - citations/references_Biomass_validationKNN.bib
  - citations/references_LandRManual.bib
csl: citations/ecology-letters.csl
link-citations: true
documentclass: book
github-repo: CeresBarros/LandR-Manual
description: "A manual for the LandR ecosystem of SpaDES modules"
---

<!-- manual version TODO: link to date and commit of manual/project repo -->

# LandR Manual

LandR is a collection of `SpaDES` modules [see @ChubatyMcIntire2019] which are aimed at simulating forest dynamics across large spatial scales, while taking into account various disturbances that affected them (e.g., wildfire and climate change), as well as their interactions with other components of forest systems, such as bird communities and ungulates (via changes in the habitat of these species) or carbon cycling.

The present manual is a "live" document, in that will grow and change according to the existing number of LandR modules, as well as their development. In addition, sub-manuals may be produced describing smaller collections of LandR modules -- e.g., the LandR Biomass manual describes only the LandR modules that are essential for the simulation of the vegetation components of forest succession, hence excluding fire disturbance modules.

```{r setup, include = FALSE, eval = FALSE}
if(!require("Require")) {
  install.packages("Require")
}
# Require::pkgSnapshot("packages/pkgSnapshot.txt")
# Much later on a different or same machine
Require::Require(pkgSnapshot = "packages/pkgSnapshot.txt")

## automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), "bookdown", "knitr", "rmarkdown",
  "SpaDES.core", "SpaDES", "SpaDES.experiment", "reproducible",
  "LandR", "Require"
), "citations/packages.bib")

## collapse all chapter .bib files into one - NOT WORKING
# bibFiles <- list.files("citations/", "references_", full.names = TRUE)  ## add package.bib
# bookYML <- ymlthis::as_yml(yaml::read_yaml("_bookdown.yml"))
# bookYML <- ymlthis::yml_citations(bookYML, bibliography = bibFiles,
#                                   csl = "citations/ecology-letters.csl",
#                                   link_citations = TRUE)
# file.remove("_bookdown.yml")  ## to avoid ymlthis::use_bookdown_yml prompting a decision
# ymlthis::use_bookdown_yml(bookYML, path = ".")

## strip YML
readLines()
```
